version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: /tmp/outlier-web
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: /tmp/outlier-web
          paths:
            - build/*
  deploy:
    machine:
      enabled: true
    working_directory: /tmp/outlier-web
    steps:
      - attach_workspace:
          at: /tmp/outlier-web
      - run:
          name: Deploy to S3
          command: |
            tar -czf build.tar.gz build
            aws s3 cp build.tar.gz s3://${AWS_S3_BUCKET}/web-dist/${CIRCLE_TAG}.tar.gz --region ${AWS_S3_REGION}

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
